[project]
name = "datascience-ecl-be2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pytest>=9.0.1",
    "scikit-learn>=1.7.2",
]
[tool.pytest.ini_options]
pythonpath = ["."]